IGNORE_CONFIG_FILE: false

activeBendingSettings:
  bendingMenuDuration: 200
  leftBendingHeight: 35.0
  leftBendingWidth: 35.0
  leftXPosition: -35
  leftYPosition: 5
  middleBendingHeight: 50.0
  middleBendingWidth: 50.0
  middleXPosition: 0
  middleYPosition: -30
  rightBendingHeight: 35.0
  rightBendingWidth: 35.0
  rightXPosition: 50
  rightYPosition: 5
  shouldBendingMenuDisappear: true
  shouldBendingMenuRender: true
airRenderSettings:
  airBurstSphere: true
bendingCycleAlpha: 0.75
chiBarAlpha: 0.625
chiBarSettings:
  chibarDuration: 200
  heightScale: 1.100000023841858
  shouldChiMenuDisappear: false
  shouldChiNumbersRender: true
  shouldChibarRender: true
  widthScale: 1.100000023841858
  xPos: 115
  yPos: 3
displayGetBendingMessage: true
fireRenderSettings:
  fireB: 10
  fireG: 50
  fireR: 255
  flameStrikeSphere: false
  lightningB: 252
  lightningG: 255
  lightningR: 135
  showFlameStrikeOrb: false
  solidFlameStrikeParticles: true
  solidFlamethrowerParticles: false
nameConflicts:
  fire_redirect: false
  explosive_pillar: false
  slipstream: false
  sandstorm: false
  cleanse: false
  ice_prison: false
  wave: false
  ravine: false
  air_gust: false
  lightning_spear: false
  sand_prison: false
  fire_shot: false
  air_bubble: false
  flamethrower: false
  lightning_redirect: false
  earth_control: false
  immolate: false
  fireball: false
  ice_burst: false
  flame_glide: false
  lightning_arc: false
  air_burst: false
  restore: false
  water_bubble: false
  water_blast: false
  flame_strike: false
  cloudburst: false
  earth_redirect: false
  water_arc: false
  airblade: false
  explosion: false
  lightning_raze: false
  earth_spikes: false
  air_jump: false
  water_skate: false
  mine_blocks: false
  wall: false
nameKeymappings:
  airblade: null
particleSettings:
  collideWithBlocks: true
  collideWithParticles: true
  releaseShaderOnFlashParticleRender: true
  voxelFlashParticles: false
radialMenuAlpha: 0.75
shaderSettings:
  bslActive: false
  sildursActive: false
  useCleanseShaders: false
  useImmolateShaders: false
  useRestoreShaders: false
  useSlipstreamShaders: false
useCustomParticles: true
